### ISSUE TITLE
RevUC

### ISSUE THREAD

**Issue by crowelch** [kfechter/RevUC-WPApp#1]
You know you can't start working on projects before the hackathon, right?

**Comment by kfechter** [comment]
This is the app from last year? duh. plus I might not even be able to go.

**Comment by kfechter** [comment]
the parse one.

**Comment by crowelch** [comment]
Lol well why did you just create the repo?

**Comment by kfechter** [comment]
Moving projects from TFS so I can start a new project on TFS.

**Comment by kfechter** [comment]
plus, this doesn't really need to be closed source. although I may have forgotten to scrub my API keys

**Comment by kfechter** [comment]
Fixed.

**Comment by crowelch** [comment]
You should also change those, there are bots that scrape looking for keys on github

**Comment by kfechter** [comment]
welp. I can't actually change them. I think jonah owns the project

**Comment by kfechter** [comment]
but i scrubbed the files
